# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e048c650526f4f45cb12b19280197d391775f430a30cbdcbd585ed585f2e7c91e86d4424a5238102857760dd2c895647abe71cb0ec34ee519cbf3a6a7c9d5ddb

test:
  secret_key_base: 6e1a42f62145e9e8009438a6e565f4653c1a8d65e952a93c1558d0aace35da7940285e6fd6126e913043e45678abdba5ee0a3d1a35b93f94f02ab9340aa52aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
